### ISSUE TITLE
Please slove the issue anyone 

### ISSUE THREAD

**Issue by AnkitkrGuptaa** [ProgrammingHero1/romantic-alexa#30]
`
![1608652675590](https://user-images.githubusercontent.com/76488124/102907840-9af0ee80-449c-11eb-98d6-bc1cac395fc5.jpg)

**Comment by lbracko** [comment]
I get the same error on MacBook!

**Comment by Stroper111** [comment]
The problem is in the bare `except` statement.

```python
def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
    except:
        pass
    return command
```

It is hiding any error that you are getting, and instead it goes directly to the `return command` part.
This command is then not yet available.

You can either display the error yourself:

```python
except Exception as e:
     print(e)
return command
```

or instead of the pass, return a command that indicates that it went wrong.

**Comment by whoschisa** [comment]
bro its still showing wrong

**Comment by whoschisa** [comment]
and there are other errors also 
that too a lot

**Comment by ashraf-minhaj** [comment]
See issue #5
